name: Test

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true
    - name: Run tests
      run: swift test
